//=========================================================
// src/atusbprog_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8UB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
#include "efm8_usb.h"
// [Generated Includes]$

#include "debug_uart.h"
#include "pwr.h"

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup(void) {
	WDTCN = 0xDE;
	WDTCN = 0xAD;
	// $[SiLabs Startup]
	// [SiLabs Startup]$
}

// TODO: move this somewhere
static void delay(uint16_t ticks)
{
	volatile uint16_t tickctr = ticks;
	while(tickctr--) {
		;
	}
}

static void release_reset(void)
{
	// Pulse the reset line on the Atmel C51.
	PIN_AT_RST = 1;
	PIN_AT_OE_N = 0;

	delay(16000);
	PIN_AT_RST = 0;
	delay(16000);

	PIN_AT_OE_N = 1;
}

SI_SEGMENT_VARIABLE(bootBanner[], const char, SI_SEG_CODE) = "\r\n--- ATUSBPROG ---\r\n";

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main(void) {
	// Call hardware initialization routine
	enter_DefaultMode_from_RESET();
	debug_uart_init();

	release_reset();

	/* Print boot banner */
	debug_uart_write_buf(bootBanner, sizeof(bootBanner) - 1);

	while (1) {
// $[Generated Run-time code]
// [Generated Run-time code]$

		PWR_enterIdle();
	}
}
