//=========================================================
// src/atusbprog_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8UB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
#include "efm8_usb.h"
// [Generated Includes]$

#include "pwr.h"

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup(void) {
	WDTCN = 0xDE;
	WDTCN = 0xAD;
	// $[SiLabs Startup]
	// [SiLabs Startup]$
}

static void write_banner(void) {
    unsigned char sfr_save = SFRPAGE;
    SFRPAGE = 0x20;
    SBUF1 = 'B';
    SBUF1 = '\r';
    SBUF1 = '\n';
    SBUF1 = '0';
    SFRPAGE = sfr_save;
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main(void) {
	// Call hardware initialization routine
	enter_DefaultMode_from_RESET();

	write_banner();

	while (1) {
// $[Generated Run-time code]
// [Generated Run-time code]$

		PWR_enterIdle();
	}
}
